//let bauch: Path2D = new Path2D();
//            bauch.moveTo(this.x, this.y);
//            bauch.quadraticCurveTo(this.x + 75, this.y - 100, this.x + 200, this.y - 30);
//            bauch.quadraticCurveTo(this.x + 230, this.y - 60, this.x + 250, this.y - 60);
//            bauch.quadraticCurveTo(this.x + 275, this.y - 45, this.x + 250, this.y - 30);
//            bauch.quadraticCurveTo(this.x + 275, this.y - 15, this.x + 250, this.y);
//            bauch.quadraticCurveTo(this.x + 275, this.y + 15, this.x + 250, this.y + 30);
//            bauch.quadraticCurveTo(this.x + 275, this.y + 45, this.x + 250, this.y + 60);
//            bauch.quadraticCurveTo(this.x + 230, this.y + 60, this.x + 200, this.y + 30);
//            bauch.quadraticCurveTo(this.x + 75, this.y + 100, this.x, this.y);
//            crc.fillStyle = "blue";
//            crc.fill(bauch);
//            crc.stroke(bauch);
//            let auge: Path2D = new Path2D();
//            auge.moveTo(this.x, this.y);
//            auge.arc(this.x + 50, this.y - 20, 8, 0, 10);
//            crc.fillStyle = "white";
//            crc.fill(auge);
//            let pupille: Path2D = new Path2D();
//            pupille.moveTo(this.x, this.y);
//            pupille.arc(this.x + 50, this.y - 20, 5, 0, 10);
//            crc.fillStyle = "black";
//            crc.fill(pupille);
//# sourceMappingURL=bigNemo.js.map